### ISSUE TITLE
There's this new Documentation thing. What of it?

### ISSUE THREAD

**Issue by Aralun** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#10]
Documentation beta [just went live](http://blog.stackoverflow.com/2016/07/introducing-stack-overflow-documentation-beta/).

Are we going to be involved in moderating it?

If so, what are our options? Is there any pitfalls we should watch out for according to our rules and ethics?

Should we, as a room, become proactive when it comes to moderating this content or judging / improving the current moderation paradigm?

**Comment by ryanyuyu** [comment]
I'd prefer leaving Documentation out of SOCVR's scope.  I think it would be more focused to create/join another room more concerned with moderation of Documentation.  While SOCVR has been involved in many aspects of SO moderation, Documentation's moderation is slightly different.  For example, there's really no such thing as "too broad" in Documentation.  

As far as being proactive, I think general MSO interaction when stuff arises on Documentation is sufficient.  Still probably worth discussing for the meeting though.

**Comment by gunr2171** [comment]
Right now (as of this writing) Documentation is going through.... growing pains. Depending on how stable the system is (rep, moderation, etc), we might need to push this topic back and result to the default "it's not main, don't deal with it".

**Comment by rschrieken** [comment]
Although ignoring might be strategy,  due to its close integration with the Rep system it does influence us. I'm thinking about our reputation requirements as the most direct issue. Don't deal with it might not be the best option here @gunr2171

**Comment by Tunaki** [comment]
@rschrieken IMO, the idea is more "don't deal with it now" rather than "don't deal with it ever". Documentation is still refined / developed as we speak and we don't know what will eventually come out of it: maybe nothing and the whole thing was a flop, maybe something marvelous with real moderation-work involved (i.e. with mods, penalties, definite rules...). As users, we can't moderate effectively what we don't know.

**Comment by braiam** [comment]
While moderation per-se can't be done in the way of the main site, it may be able to be done with helping hand on pressing issues like spam and plagiarisms, which are important for the development of the site. Enforcing SE's two most clear cut no-go, given Docs characteristic that there are no global queue, but isolated tags, keeping the obviously unacceptable in check may be recommendable.

**Comment by NathanOliver1** [comment]
Conclusion:

We will only moderate docs for rude, abusive, spam, plagiarism and unforeseen abuse.

http://chat.stackoverflow.com/transcript/message/32060327#32060327
