### ISSUE TITLE
Jugs and Politics

### ISSUE THREAD

**Issue by drewpierce** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#16]
There shall be complete censorship of chatter concerning Jugs and Politics (including anarchy)

**Comment by Tunaki** [comment]
To that list, I guess we can add Gender, Religion, Terrorism, Racism, Sex... and even Waffles. I'm not a fan of a list of banned topics -- this is a slippery slope. People should use their common sense, and go by the Be Nice policy. You can't rely on other persons having a thick skin (although they probably should).

**Comment by dorukayhan** [comment]
> and even Waffles

What do waffles have to do with this?

**Comment by magisch** [comment]
I'm not a fan of blanket bans. We're adults here, we can make adult decisions and use common sense here.

**Comment by Tunaki** [comment]
Closing due to the previous comments and general feedback received: we don't want that.
