### ISSUE TITLE
"Be Nice" topic

### ISSUE THREAD

**Issue by tripleee** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#17]
The room went through some convulsions in mid-September.  The purpose of this topic is to try to close the matter with a bit of guidance going forward.

We are looking for **closure,** not pro and con arguments.

Of course, if there is something you would like to propose in order to help the room handle similar incidents better in the future, that's fine.  But let's look forward, not back.

**Comment by Undo1** [comment]
What (type of) guidance are you thinking? Ultimately, this is an issue that should be solved at the network level... but that's hard.

**Comment by tripleee** [comment]
Maybe not much more than "that wasn't our proudest moment, let's not go there again" for this particular incident.

**Comment by Tunaki** [comment]
[Bookmark](https://chat.stackoverflow.com/rooms/108179/conversation/2016-october-topic-2)

This was a single isolated incident that evolved into a big drama for really nothing. I think every party involved, including the RO team, understood what went wrong and learned from it. In the future, we'll try to be more responding to issues currently rising in chat, but I'll add that everyone leads by example.

Just be nice. If you see something flagged and it could be inappropriate respect that someone felt that way and move on. We deal with people of all types from all over the world. There are going to be clashes and people are going to view things differently. Moving forward we just need to be more mindful of what we are saying and we need to not overreact if something gets flagged.
