### ISSUE TITLE
Let's stop arguing daily about the appropriateness of close votes on specific questions

### ISSUE THREAD

**Issue by drewpierce** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#18]
</eom>

**Comment by Tunaki** [comment]
Discussing close reasons and their scope on specific questions is on-topic for the room. Is this subject raised with regard to:
- the length of those discussions when they arrive?
- the frequency with which they happen?
- the specific typo reason?

And what is the current issue with this subject?

**Comment by Tunaki** [comment]
Clarification:

> We have 25 brains in this room. Not one master brain and 24 clones of it. We make our own choice

The topic raised here is that discussions about whether or not a close / reopen vote is warranted are sometimes too long, which results in it being repetitive and not constructive.

The question is: is the room ok with it, and, if not, what is the point at which it becomes too long?

**Comment by tripleee** [comment]
Outlawing such discussions seems anathema to the room's purpose.  Limiting them with strict rules seems premature to me.  My proposal would be to try to articulate an informal guideline for when to call quits on such discussions.  Maybe two or three "shut up" comments from different members?

**Comment by Tunaki** [comment]
[Bookmark](https://chat.stackoverflow.com/rooms/108179/conversation/2016-october-topic-3)

This is pretty much already covered in the FAQ: 4. Avoid extended discussion about a cv-pls. We don’t have to agree about a close request. We’re not a democracy. However, users that are posting cv-pls’es that are blatantly wrong will be told so. The final verdict is on the RO team.

If you're having a back-and-forth between two well-defined 'teams', it's gone too long. You know when you hit that point. A blanket ban on discussion about cv-pls requests would defeat the purpose of the room and be unhealthy. Once you start repeating reasons for open or close you are just hitting a dead horse. No reason to keep going on.
