### ISSUE TITLE
Should room owners be moderating room members actions outside of the room?

### ISSUE THREAD

**Issue by Tunaki** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#20]
It is fairly obvious that a room owner should moderate actions performed within the room itself.

As far as advising moderation practices for other users, everyone should be engaging in such discussions. While it may be nice to think that room owners are somehow more of an authority on such matters than regular users, they are not.

Are room owners responsible for, and should room owners be moderating (above and beyond providing advice), actions by regular members made outside of the room, such as close voting, delete voting, editing, reviewing, etc.

**Comment by gunr2171** [comment]
Does this means "regulars", or all users in SOCVR?

**Comment by tripleee** [comment]
Not really sure what you are getting at here.  "Are room owners responsible for room members" I think is either a straw man (you want us to say a resounding no, and throw this in as a _reductio ad absurdum)_ or, if you really mean it, a quick way to make sure there are no room owners (or perhaps I should add, no room owners whom anybody would want to see as room owners -- you will repel responsible people, and potentially attract little Hitlers to fill the void).

**Comment by AWegnerGitHub** [comment]
What do you mean "responsible"? 

What are the consequences on the room owner if a user performs these moderation actions inappropriately? What are the consequences if a meta post is created calling out one or more users?

**Comment by Tunaki** [comment]
[Bookmark](https://chat.stackoverflow.com/rooms/108179/conversation/2016-october-topic-4)

The room owners are not moderators. If something needs moderating, get a moderator. If it's a room issue, handle it in the room.

Let alone we can't do that effectively, we don't even want to do that. People outside of the room can do as they want, as long as they follow SO rules and guidelines. Of course, when links to questions are left in the room, it is expected that they follow the room's rules. But we can't kick a user because we disagree with something they commented on Main or Meta.
