### ISSUE TITLE
Room owner coverage

### ISSUE THREAD

**Issue by magisch** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#21]
Do we want to work towards a situation where we have enough (and distributed throughout the timezones enough) room owners so that at least one is online at any given time? 

That would certainly solve a lot of room-moderation problems.

**Comment by rschrieken** [comment]
Like what kind of lot of problems? If you're thinking about the problems caused by regulars because they forget to lead by example, or moderate among themselves I don't think more RO's will help. A change in attitude might.

**Comment by magisch** [comment]
@rschrieken Failing a permanent change of attitude of some members (which I don't think is short or mid-term feasible atm) having a room owner in the room tends to keep conversations on topic and non-inappropiate near automatically. You'll note that these big dramas only happen when there isn't a room owner to put on the brakes.

Even leading by example, for instance during the last big sexism debate, multiple people tried to put a stop to it. Its just that we can't really do anything outside of telling people to cut it. If they won't cut it, they won't.

A room owner can do more in these scenarios.

**Comment by AWegnerGitHub** [comment]
I agree with @rschrieken. The goal shouldn't be 24 hour coverage, it should be better community behavior and "lead by example".

**Comment by Tunaki** [comment]
[Bookmark](https://chat.stackoverflow.com/rooms/108179/conversation/2016-october-topic-5)

If we need an RO in the room 24/7 then something is rotten in the room, and if we can't make this room work with all of us it is not going to work with just some RO's around.
