### ISSUE TITLE
Do we still want to engage in burnination requests?

### ISSUE THREAD

**Issue by Tunaki** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#27]
Since the last burnination effort of [the `[godaddy]` tag](http://meta.stackoverflow.com/questions/331817/1743880) (and the subsequent mess on Meta: [1](http://meta.stackoverflow.com/q/333353/1743880), [2](http://meta.stackoverflow.com/q/333706/1743880), [3](http://meta.stackoverflow.com/q/333370/1743880), [4](http://meta.stackoverflow.com/q/334584/1743880)), the SOCVR has not engaged in further burnination requests. Notably, [the `[apple]` tag](http://meta.stackoverflow.com/q/333833/1743880) burnination request, that was the only one after that to be featured, was not taken by any party, and left untouched.

We've still been keeping an eye on burnination requests since then, as they are posted on Meta, but have yet to notice any progress or support past the votes on the post.

Does SOCVR still want to participate in burnination efforts? Is our moderation time, and our votes, better spent on the front page and new activities?

**Comment by Aralun** [comment]
Who else is going to do it? At this point it seems that either we run those each time, or burnination requests die altogether.

**Comment by rschrieken** [comment]
relevant MSO posts:
http://meta.stackoverflow.com/questions/260222/lets-have-a-different-burnination-process
http://meta.stackoverflow.com/questions/318426/could-we-stop-with-all-those-burnination-requests

**Comment by Tyler-H** [comment]
I think we should; we are responsible for the current Meta process of burninating tags. We should follow throw and actually have some burnination sessions put on our event calendar instead of just "spend all your CVs in the CV queue" every day.

**Comment by ghost** [comment]
As much as I hate them, I think they should stay in the room. It's the most qualified and organised group of people to carry out such a task.

**Comment by Tunaki** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-january-topic-2)

No for anything longer than a week to finish. Meta has no invested support in burnination requests. "Help" from their end comes and goes like the wind. We wrote the FAQ entry for how burnination processes work, and we've been the only ones doing anything about it. We can take on <=500 post burninations (that meet site requirements), anything more we'll have to talk about

Let's have fun with some burnination, smaller ones, where less frustration builds and instead we feel fulfillment.
