### ISSUE TITLE
If you're gonna talk Politics (or any other off-topic stuff for that matter), you must respect those who disagree

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#30]
[Background](http://meta.stackexchange.com/questions/289398/if-youre-gonna-talk-politics-you-must-respect-those-who-disagree)

We already have the rule that it is [OK to disagree](http://socvr.org/faq#general-expectations-for-members) bit that is more geared towards our normal operation, not to the general chatter.

Given the concern raised by Shog9 in his post, do we need extra guidance on how to keep all our off-topic discussions under control? 

Or do we end up with [this](http://meta.stackexchange.com/questions/289398/if-youre-gonna-talk-politics-you-must-respect-those-who-disagree#comment939392_289398):

> ...  you also need chatter to attract some crowd and keep it lively. You can't only talk about the weather or what you had for breakfast...

**Comment by Tunaki** [comment]
I disagree with this topic request.

**Comment by Undo1** [comment]
If the network wide / site rules aren't good enough, let's fix those. This isn't something that needs to be handled at an individual room level; I also disagree with this request.

**Comment by Tiny-Giant** [comment]
While this topic may have been touched on before, I believe that—given recent events—there is no harm in bringing this up again and reaffirming our position on the matter. As far as I can tell, the point of the meta post is: "If you're going to talk about politics, do it respectfully, as you should with all discussion". While this may seem redundant, it may benefit us to bring it up again.

**Comment by Cerbrus** [comment]
Isn't this basically covered in the room rules already? "Be nice":

> No matter what is asked from us, we moderate the post and educate the user, the be nice policy is our bible. ([source](http://socvr.org/faq#common-questions))

**Comment by arp242** [comment]
Have there been concrete problems?

**Comment by Tunaki** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-january-topic-7)

All discussions should be respectful and professional, regardless of topic. If discussion gets too far off-topic, it is everyone's responsibility to steer the direction back on-topic. Too much of any off-topic discussion is bad. Be Nice applies in the room, and any off-topic discussion that is too lengthy should be moved. if you want to do that disagree or debate thing, go into your own room.

The network as a whole has policies that control discussion (Be Nice). The room has a specific topic and it's necessary to have some extra policies, about that topic, but it also just needs to embrace network-wide policies, like Be Nice; there's no reason to add anything to them.

At the request of any RO, we should stop discussion of a given topic or move it elsewhere.
