### ISSUE TITLE
Can we fix Closey? Or implement an old, known working version?

### ISSUE THREAD

**Issue by Tyler-H** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#35]
Closey has been in a coma for months. I'd like to discuss a possible path to getting Closey back in a working state, either with fixes/upgrades, or a rollback to a known working iteration. 

The metrics and interaction provided by Closey were a big part of what drove SOCVR users to participate in Close Events, Tag Burninations, etc., and those have suffered during Closey's illness. As a result, overall site quality suffers, too.

**Comment by ArcticEcho** [comment]
Just want to drop this by here as I won't be online for the meeting. I've been inactive over the past few weeks (as you've probably noticed), and thus haven't been able to continue fixing her. I do hope to be back in action starting from the 25-26th of this month (and have Closey up and running soon after).

Currently the only thing stopping (the latest version of) Closey from being ran at the moment is her tracking library, it's buggy. Booting up an old version should be relatively easy, it's just a matter of finding a suitable commit to build/deploy.

**Comment by Tunaki** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-january-topic-5)

Yes, Sam is on it. Time for repairs: 6 to 8.
