### ISSUE TITLE
Does the room/group need to be renamed to reflect the fact that it doesn't focus only on "Close" activity?

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#6]
This item was postponed from last meeting: http://chat.stackoverflow.com/rooms/108179/conversation/2016-april-topic-3-part-1

**Comment by NathanOliver1** [comment]
Conclusion:

SOCVR is so ingrained that at this point it is impossible to change without confusion.  Even though our reach has expanded close voting is still a major part of what we do.  We will not be changing the name

http://chat.stackoverflow.com/transcript/message/32059787#32059787
