### ISSUE TITLE
Do we need more *-pls options directly in the CV-PLS userscript?

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#7]
Examples could be but are not limited to:
-  comment-pls  leave an autocomment
-  edit-pls someone needs to edit this
-  cv-query-pls any suggestion for a close reason
-  answer-pls  this poor question can use a good answer
-  _your option here_

**Comment by Tunaki** [comment]
waffle-pls
onebox-pls
train-pls

**Comment by NathanOliver1** [comment]
Conclusion:

Yes we want to do reject-pls but we need to sit down and document the cases for such and then test.  Candidates are: ties going the wrong way, obvious spam,rude,abusive and plagiarism.

http://chat.stackoverflow.com/transcript/message/32059909#32059909
