### ISSUE TITLE
What is the line for reporting 'all spam' or 'all bad suggested edits' for a particular user?

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#8]
Smokey has an "all spam" feature, which allows a person to tell the smokey network that every single post by a given user is spam.

We also have found cases where a user make many, many suggested edits which should be rejected.

What is the line here? Should we be doing this more often? Would doing this more often make our room bad as we would be targeting users?

**Comment by double-fault** [comment]
@gunr2171 I'm not sure about the too many bad edits thing, but I don't think we need to disable `allspam` on smokey for SOCVR.

A [search reveals](http://chat.stackoverflow.com/search?q=!!%2Fallspam&room=41570) that `allspam` has been used only 7 times since April start to the current date. This command is mainly used in Charcoal, and very rarely in SOCVR. 

Rene had even left a message regarding the "don't target user", which told that "all spam" was kinda ok:

> Remember people: Users that had the habit to pick a single profile and go over their posts, flagging, voting, deleting, commenting have been suspended before. I don't want anyone from this room to be suspended or run the risk of being suspended. That is the sole reason the rule: vote on the post not on the user exist. And that is why I don't want to see user links here but only post links. Only exception is Smokeys allspam command where you still flag single posts. 

If `allspam` is being abused and used too much, I think we might disable it. But for now, with so less use, I think we can let it remain.

**Comment by rschrieken** [comment]
@Fortunate-MAN  we bring it up because I rather have a _no links to users_ rule then a rule with (many/growing)  exceptions that are also hard to moderate in the room  and / or make no sense when the situation dictates that.

**Comment by double-fault** [comment]
@rschrieken Ah. I see your point. If the rule is for no user profile link, I think disabling `allspam` would be alright. At first I thought this issue for mainly only disabling allspam, not all links.

**Comment by ArtOfCode-** [comment]
@rschrieken Does it matter for spammers? `!!/allspam` is intended for cases where literally _all_ of this user's posts are spam; does it really matter if people go over their profiles to cast spam flags? I'd imagine not - the user's going to be destroyed soon enough anyway.

**Comment by rschrieken** [comment]
@ArtOfCode-  I don't think it does but the topic is brought up because we want to hear the room consensus on the topic. Maybe my silly rule is to strict, maybe not. I hope we get some clear guidance out of this discussion

**Comment by NathanOliver1** [comment]
Conclusion:

Unless posted by a moderator we will not post links to users.  This means no allspam and no reject-all.  Our rule is no links to a user profile

http://chat.stackoverflow.com/transcript/message/32060005#32060005
