### ISSUE TITLE
How do we talk about the room?

### ISSUE THREAD

**Issue by Aralun** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#9]
There's a fine line between talking about / trying to promote the room and... well, spamming and pissing people off. How do we / should we advertise the room? Does it make a difference if it's main or Meta?

Should we have any guidelines on the matter?

**Comment by NathanOliver1** [comment]
Conclusion:

Guideline: If it is relevant to the conversation at hand, fine. If it is out of the blue then just don't do it.
That said On main, you don't say anything unless someone directly asks. On meta, you can give some details if SOCVR could be relevant/useful in a discussion

http://chat.stackoverflow.com/transcript/message/32060212#32060212
